# LambdaTest Configuration

# Project and folder configuration
project_id: "01J5WNZN22430W982GN6W9QERF"
folder_id: "01J5WNZN2KC98H2XX2EX5ZGPNT"

# Test Run configuration
assignee: 3152569
environment_id: 209861

# Test URL for automation
# test_url: "https://demo.lambdatestinternal.com"
